### PR TITLE
Add support for 5.2 auth config

### LINKED ISSUE #116: Laravel 5.2 upgrade
Hi,

I just upgraded to Laravel 5.2 and I get an error on any route that uses laravel-acl Roles: 

image

After a long debugging it seems that in laravel 5.2 the [config\auth.php](https://github.com/laravel/laravel/blob/master/config/auth.php) file was changed a "little". 

```javascript
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

In short the laravel-acl [Role.php](https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Models/Eloquent/Role.php) model calls a non existing item in:

```javascript
public function users()
    {
        return $this->belongsToMany(config('auth.model'))->withTimestamps();
    }
```

Instead if i change to bellow block it works, the Fatal error disappears and everything is back to normal:

```javascript
public function users()
    {
        return $this->belongsToMany(config('auth.providers.users.model'))->withTimestamps();
    }
```

Is there anything that can be done for the next release of laravel-acl to contain this fix for laravel 5.2?

Thank you.

### PR DESCRIPTION
**Pull request by uzegonemad**
This closes #116 by checking for 5.2's config style with a fallback to 5.1.

### CODE REVIEW

**Comment by kodeine** [comment]
@uzegonemad Thanks

**Comment by uzegonemad** [comment]
@kodeine I just realized I only handled it for `Role` but not `Permission` -- do you want me to submit another PR fixing the issue or do you want to handle it?

**Comment by kodeine** [comment]
@uzegonemad 
please send the PR, i'd really appreciate.

Thanks

**Comment by uzegonemad** [comment]
@kodeine I submitted another PR. Sorry for the oversight!

**Comment by kodeine** [comment]
@uzegonemad no problem.

**Pull request merged**
