### PR TITLE
Laravel 6.0 Support

### PR DESCRIPTION
**Pull request by alec-joy**
Breaks compatibility with previous versions of Laravel and PHP versions before 7.0 (though Laravel 6 requires 7.2)

### CODE REVIEW

**Comment by kodeine** [comment]
awesome, let me review this

**Comment by kodeine** [comment]
looks like we got test errors.

**Comment by alec-joy** [comment]
The publishMigrations method on master was (rightly) changed to loadMigrations, I just got rid of it all together to use the new method of migration loading described [here](https://laravel.com/docs/master/packages#migrations)

I should have pulled master before making changes, that's on me haha. I was working off the 1.0 branch.

**Comment by kodeine** [comment]
lol no worries, as soon tests pass, we'll be good to go with merge! thank you for your time and efforts.

**Comment by kodeine** [comment]
yup that would be perfect! please do so.

**Pull request merged**
