### PR TITLE
Added:  Different guard support

### PR DESCRIPTION
**Pull request by CodeIgor**
**This fixes handling of a different guard other than application default.**

Fixes: #135.

- Guard parameter on config file to get default;

```php
  /**
   * Guard
   * Set the guard for user validations.
   */
  'guard' => config('auth.defaults.guard'),
```

- Added guard on  HasPermission handle;
```php
   $this->guard = config('acl.guard');
```

- Added `$guard = $this->guard`  on hasRole, hasPermission and protectMethods;

- Changed `$request->user()`  to `$request->user($guard)` on hasRole, hasPermission and protectMethods;

- Changed Blade directives to `Blade::if` method and guard added;
```php
   // role
   Blade::if('role', function ($expression) {
        return Auth::guard(config('acl.guard'))->check() && Auth::guard(config('acl.guard'))->user()->hasRole($expression);
   });

   // permission
   Blade::if('permission', function ($expression) {
        return Auth::guard(config('acl.guard'))->check() && Auth::guard(config('acl.guard'))->user()->hasPermission($expression);
   });
```

### CODE REVIEW

**Comment by kodeine** [comment]
@CodeIgor could you please update the readme file as well to support this update

**Review by kodeine — APPROVED** [review]

**Comment by kodeine** [comment]
@CodeIgor sorry for very late reply, it just slipped from my todo list.

So, `endpermission` and `endrole` was removed, can we make it backwards compatible?

**Comment by CodeIgor** [comment]
@kodeine done, i changed the used directive back to how it was

**Comment by kodeine** [comment]
Thank you!

**Pull request merged**
