### PR TITLE
Support for Laravel 5.3

### PR DESCRIPTION
**Pull request by peetersdiet**
solves #149 

## Changes
- Renamed HasRole::is() to HasRole::hasRole() due to conflicts with new
  method Model::is() in Eloquent
- Corrected all Blade directives to handle change in $expression parameter
  passing (no more brackets included).
- Using Collection::pluck instead of Collection::lists(), if the method
  exists.
- Preserved compatibility with older Laravel versions.

## Testing:
I updated the complete library, but only did functional testing on Laravel 5.3 with the hasRole trait, because that's the only one we use for now.
For the other changes I only did an automated syntax and a thorough visual check.

I am quite confident that nothing broke, but if someone can test the other Traits and/or on prior Laravel versions, that would be appreciated.

### CODE REVIEW

**Comment by kodeine** [comment]
I think this should be in a new branch otherwise people using 5.2 this will conflict right?

**Comment by peetersdiet** [comment]
@kodeine Indeed, the change from is() to hasRole() will break for laravel < 5.3 , if developers don't do (minimal) modifications. The other changes will normally work on older versions. I did the rename, because it was the most straightforward.

There are other options:
1. Introduce a new Trait for Laravel >= 5.3. E.g. hasRole53 .
2. Change nothing, but demand a minimal change of developers when upgrading: map the new Trait method HasRole::hasRole() to the old HasRole::is(). This is easy and fully supported by the PHP language. Something like this:
```php
class User {
    use HasRole {
        hasRole as is;
    }
}
```
3. Dynamically generating the Trait-classes, based upon the laravel version. This will preserve code copletion in IDE's.
4. Dynamically catching is/hasRole, using __call(), but this would be quite intrusive for projects, as we hijack the __call method of the class using the Trait.

Option 1 would be fullly free of conflicts. No new branch, less maintenance and code divergence.
I based my change on option 2, which I would choose. Strictly speaking, this would require an upgrade of the major version number as it introduces breaking changes, if you use semantic versioning (composer recommended). This would also require a new branch, as you state. On the other hand you could just up the minor version and keep the branch, as it's very easily mended by mapping the Trait-method and also, I notice Laravel doesn't really care about these things either, as they introduce breaking changes upon changing the minor version number.

Let me know what you think is the way forward, and If I have to make any modifications and/or change the base branch of the PR.

**Comment by peetersdiet** [comment]
@kodeine: If you create a new branch 2.0, I will rebase to that.

**Comment by peetersdiet** [comment]
I accidently clicked close PR, sorry for any spam.

**Comment by peetersdiet** [comment]
@kodeine: I have been thinking about a solution that doesn't involve branching and maybe I found one. 

Correct me if I'm wrong, but two key points arise:
1. Traits are at the language level, so we have to be able to catch the implementation-switch in the HasRole trait at this level.
2. Composer is only to manage dependencies, so we cannot use it to dynamically make a switch on the laravel version number (as laravel-acl does not depend on laravel).

I think an option would be to implement a custom autoloader only for the "Kodeine\Acl\" namespace, and use that to switch HasRole implementations (files) upon loading of the class.

I have researched it a bit, and this looks like a solution to [allow a custom classloader in composer](https://github.com/composer/composer/issues/1493) . If you want, I can try to make it work like this.

**Other references**
[the composer autoload docs](https://getcomposer.org/doc/04-schema.md#autoload)

**Comment by peetersdiet** [comment]
@kodeine: It's a bit unorthodox, but I found a way to avoid branching. Please review the diff below. If you're happy with this, I'll merge it into this PR.

```diff
diff --git a/src/Kodeine/Acl/Traits/HasRole.php b/src/Kodeine/Acl/Traits/HasRole.php
index 1619008..982feda 100644
--- a/src/Kodeine/Acl/Traits/HasRole.php
+++ b/src/Kodeine/Acl/Traits/HasRole.php
@@ -1,7 +1,7 @@
 <?php namespace Kodeine\Acl\Traits;


-trait HasRole
+trait HasRoleImplementation
 {
     use HasPermission;

@@ -253,3 +253,18 @@ trait HasRole
         return parent::__call($method, $arguments);
     }
 }
+
+$laravel = app();
+if (version_compare($laravel::VERSION, '5.3', '<')) {
+    trait HasRole
+    {
+        use HasRoleImplementation {
+            hasRole as is;
+        }
+    }
+} else {
+    trait HasRole
+    {
+        use HasRoleImplementation;
+    }
+}

```

**Comment by kodeine** [comment]
let merge this final PR and then we need to update the docs to reflect on how to use on laravel 5.3.
Eventually i was thinking we should remove support of earlier versions and just proceed with 5.3 >.

There's another PR #132 which uses caching so if you have time can you test that PR with 5.3?

**Comment by peetersdiet** [comment]
By final PR, do you mean with the aforementioned diff, or without? Let me know, and I will adjust the PR accordingly, so you can merge.

My choice would be to include the diff to ensure full backwards compatibility for now, and add a deprecation notice in the docs that the is() method will be removed in some later version. That gives developers on Laravel <5.3 the time to adjust.

I would ensure backwards compatibility at least until 5.1 is no longer the LTS version.

The only con against the diff is that it's not strictly PSR-4 compliant, because we define 2 classes in 1 file. Imo, that's neglible compared to the benefits.

## PR #132
As for the PR #132, I'll try to test it next week.

## Sidenote on __call
By creating the diff above, I noticed that HasRole implements the __call-method. It's considered bad practice: a Trait should avoid overwriting magic methods, especially not in a library. 

This is because multiple Traits cannot overwrite the same method. To avoid clashes, developers have to map conflicting magic methods to other methodnames, and then use those mapped methods from within their own implementation of their magic methods.

Now that we're talking deprecations regarding HasRole, maybe it's an option to split of the call in another Trait, e.g. HasRoleMagic, and not load it by default . This way developers have to consciensly make a decision to use it and overwrite __call.

Just a thought. (And maybe something for another discussion thread.)

**Comment by kodeine** [comment]
@peetersdiet 
I think lets go with the aforementioned diff.

regarding `__call` i think we can separate it to HasRoleMagic and move that to master branch. Lets keep 1.0 branch for <5.3 and master would be supporting >= 5.3. Hows that sound?

__call was also used to keep it easier to check permissions like method names `userCanEdit()` `isUserAdmin()`


Thanks a lot for contributing, really appreciate it. :+1:

**Comment by peetersdiet** [comment]
@kodeine: I applied the diff, so merge at will.

Regarding splitting the codebase, **I would always try to avoid branching**, especially if your time is sparse. It brings a lot more maintenance overhead to the project when maintain multiple branches vs. a single branch. To alleviate some of the maintenance burden, you can first write tests, with for example at least 90% code coverage.

The root cause for branching now is to provide backwards compatibility in the 1.0 branch. If you follow [semantic versioning ](http://semver.org/) the logical choice would be to set up a new branch called **2.0** . Composer versioning is built around semantic versioning, so I would definitely follow it.

**Comment by vanderson139** [comment]
@kodeine 

Laravel 5.2 helper "array_where" uses call_user_func($callback, $key, $value) 

But 5.3 uses array_filter which has inverted $value, $key parameters

http://php.net/manual/en/function.array-filter.php

See Kodeine\Acl\Middleware\HasPermission:120

```php
// determine crud method we're trying to protect
$crud = array_where($methods, function ($v, $k) use ($called) {
    return in_array($called, $v);
});
```

**Pull request merged**
