### PR TITLE
Update the readme to reflect new major version/some laravel specific changes **NEEDS NEW VERSIONS TAGGED

### PR DESCRIPTION
**Pull request by alec-joy**
Before merging this, in order to make it accurate, a release of 1.0 and a release of 2.0 (master) need to be tagged. While installed dependencies based on branches works, it's not ideal as there's no way to pin to a specific version the way you can with tagged releases.

### CODE REVIEW

**Comment by alec-joy** [comment]
@kodeine any updates? I know you're on vacation so no rush

**Comment by kodeine** [comment]
@alec-joy sorry it got out of my mind.

**Comment by alec-joy** [comment]
Can you tag the releases? Right now if someone follows the instructions in the readme they'll get a 4 year old version of the package that predates the 1.x branch.

**Comment by kodeine** [comment]
@alec-joy done, sorry for the late response. Please confirm if it looks good.

**Pull request merged**
