### PR TITLE
Add cache to roles and permissions

### PR DESCRIPTION
**Pull request by rafaelpv**
Add cache to roles and permissions. Add unit tests too.

### CODE REVIEW

**Comment by kodeine** [comment]
@rafaelpv 
Thanks, i will test this on my machine and will merge it. Appreciate it.

**Comment by Shipu** [comment]
hlw @kodeine are you test this pull request.... ???

**Comment by kodeine** [comment]
@Shipu are you able to test this pull? im not on my dev machine so cant test at the moment

**Comment by peetersdiet** [comment]
@kodeine I tried to test this PR under Laravel 5.3, but my changes in PR #152 were developed against your default branch (1.0), not master as seems to be the case here. I encountered several conflicts trying to merge, which imho are better resolved by @shipu or you, not me.

Also, if you look at [the changes in this PR](https://github.com/kodeine/laravel-acl/pull/132/files), I think the PR needs to be cleaned up first, because I see a lot of unneccessary changes: whitespace, renaming etc. Perhaps cleaning up and rebasing it on 1.0, can be done at the same time?

**Comment by heukirne** [comment]
@peetersdiet, just run phpcbf with PSR2 standards againt your code and it will make the same changes (whitespace) for you.

**Comment by peetersdiet** [comment]
@heukirne Formatting is not an issue, it's only my opinion that changing formatting in regular PR's is bad practice. It adds absolutely no functionality, makes the job of reviewing diffs unnecessarily more complex and can, in rare cases introduce bugs due to a bad autoformatter. Rectifying formatting issues are usually (quickly) solved once while in a codefreeze, and afterwards kept inline by automation (like tests).

On a whole, I see a lot of [changes in this PR](https://github.com/kodeine/laravel-acl/pull/132/files) unrelated to caching, such as changes in composer.json and travis.yml, as well as renaming of methods. I leave it up to @kodeine to judge on the validity of all these side-issues in this PR. He's the author afterall. I was merely pointing it out.

**Now, the real issue is, there are conflicts when merging with the *1.0* branch, which is the default repository branch. The docs state that kodeine/laravel-acl requires ~1.0@dev in composer and since master and 1.0 have diverged, I suggest @rafaelpv changes the base of this PR to 1.0 and resolves any conflicts with the current version of this library.**

It's not up to me to resolve these conflicts, it's up to the original developer, because he's in the best position to create a resolution that works as intended. And, frankly I wanted to do some quick tests as a courtesy, not add extra work to my already full schedule. No offence intended.

**Comment by heukirne** [comment]
@rafaelpv, can you make @peetersdiet suggestion?

**Comment by rafaelpv** [comment]
I made the @peetersdiet suggestions and created a new pull request #153

**Comment by kodeine** [comment]
@rafaelpv #153 looks good, i just wrote a question there, after that we can merge it! thanks for your contribution! :+1:

**Comment by kodeine** [comment]
@rafaelpv 
i see you had added tests in this PR, can you make a new PR just with tests so i can merge that as well?

Thanks a lot for your hard work! :100:

**Comment by rafaelpv** [comment]
Yes, of course. I must include Travis and composer changes or just unit tests, without automation?

**Comment by kodeine** [comment]
@rafaelpv automated would be wonderful

**Comment by heukirne** [comment]
@kodeine you can close this PR now.

**Pull request closed without merging**
