### PR TITLE
return slug with ID

### PR DESCRIPTION
**Pull request by KhaledSMQ**

### CODE REVIEW

**Comment by kodeine** [comment]
@KhaledSMQ have you tested the code, does it still work with `->lists('slug','id');` ? If so, ill merge it.

**Comment by KhaledSMQ** [comment]
hi @kodeine Thank you for replay 
It's not the best seluation to get the role ID but i think it can help to do update for roles and permissions.

```

// here is my custom update method am using roles ID to do modifications

  public function SavePermissions(Request $request, $id)
    {

        $listPermissions = [ 'companies', 'user', 'products', 'contract', 'ticket', 'coupons', 'setting', 'roles' ];
        $listPerms       = [ 'add', 'view', 'edit', 'delete' ];

        $roleAdmin = Role::find($id);
        if ($roleAdmin) {
            $permissions = $roleAdmin->Permissions()->get();
            foreach ($permissions as $key => $per) {
                if ($request->has($per->name)) {
                    $y       = [ ];
                    $current = Permission::find($per->id);
                    $perName = $per->name;
                    if (in_array($perName, $listPermissions)) {
                        foreach ($listPerms as $xs) {
                            $dd = $request->$perName;
                            if (in_array($xs, $dd)) {
                                $y[] = [ $xs => true ];
                            } else {
                                $y[] = [ $xs => false ];
                            }
                        }
                    } else {
                        $y [] = [ 'view' => true ];
                    }

                    $result = [ ];
                    foreach ($y as $value) {
                        $result = array_merge($result, $value);
                    }
                    $current->slug = $result;
                    $current->save();
                } else {
                    $current = Permission::find($per->id);
                    $perName = $per->name;
                    if (in_array($perName, $listPermissions)) {
                        $result        = [
                            'add'    => false,
                            'view'   => false,
                            'edit'   => false,
                            'delete' => false,
                        ];
                        $current->slug = ( $result );
                        $current->save();
                    } else {
                        $results       = [
                            'view' => false,
                        ];
                        $current->slug = ( $results );
                        $current->save();
                    }
                }
            }
        } else {
            Flash::error(' Can\'t found this Permissions.');
            Alert()->error(' Can\'t found this Permissions.', 'Incorrect permissions');

            return redirect()->back();
        }

        Flash::success(' Permissions has been Updated successfully.');
        Alert()->success(' Permissions has been Updated successfully.', 'Update Permissions ');

        return redirect()->back();

    }

```

**Comment by KhaledSMQ** [comment]
Sorry i didn't mention in last comment about testing , i have already test and i didn't face any issue

**Comment by KhaledSMQ** [comment]
@kodeine 

ping

**Comment by kodeine** [comment]
@KhaledSMQ 
okay im going to merge it.

**Pull request merged**
