### PR TITLE
Fix  creation of dynamic property HasPermission::$request is deprecated

### PR DESCRIPTION
**Pull request by bytestream**
https://www.php.net/manual/en/migration82.deprecated.php

### CODE REVIEW

**Comment by kodeine** [comment]
@bytestream thank you for this PR, were you able to test the change?

**Comment by bytestream** [comment]
@kodeine yep no issues 👍🏼

**Comment by Rafeethu** [comment]
Hi @kodeine, is it possible to merge this?

**Comment by kodeine** [comment]
@Rafeethu @bytestream thank you, i've merged this. sorry for the delay.

**Pull request merged**
