### PR TITLE
Add Unit Tests

### PR DESCRIPTION
**Pull request by heukirne**
add unit tests
add user model and migration

### CODE REVIEW

**Comment by heukirne** [comment]
@rafaelpv and @kodeine, I create this new PR for unit tests

**Comment by heukirne** [comment]
Looks like it's working: https://travis-ci.org/heukirne/laravel-acl

**Comment by heukirne** [comment]
Hi @kodeine ,

You need to enable laravel-acl repo at travis-ci to run tests every commit or pull request:
https://travis-ci.org/kodeine/laravel-acl

Best regards.

**Comment by kodeine** [comment]
@heukirne just enabled those :) looks like its working wohoo. Thanks for your time.

**Pull request merged**
