### PR TITLE
Add tags to the cache to easily purge ACL cache

### PR DESCRIPTION
**Pull request by screencom**
In order to purge only ACL cached entries, use the tags() method on the Cache facade. This way it is possible to purge only the ACL entries.

This functionality can be helpful when editing ACLs using an interface.

### CODE REVIEW

**Comment by kodeine** [comment]
@screencom can you please make sure the tests work before i can merge?

Thanks

**Comment by screencom** [comment]
It seems the tests fail for a reason I have no direct influence on. The tests for 5.5 succeed, but 5.6+ fail, apprantly due to this: Symfony\Component\Console\Exception\InvalidOptionException: The "--realpath" option does not exist.

**Comment by kodeine** [comment]
are you using this on any interface? i was thinking to build an interface as well so its easier to manage acl. But if you have done it already, maybe we can make it opensource?

**Comment by screencom** [comment]
Hi,

I'm not using in an interface. I'll send you the relevant code parts so you can use it for docs. 

Kind regards,
Michiel van Leening
Senior Systems Architect
 
Hoogveen 3-5
9501 XK Stadskanaal
The Netherlands
T. +31(0)85 273 64 28
m.vanleening@screencom.eu

**Comment by WickedSik** [comment]
After installing this update, I received the following error:

```
BadMethodCallException in Repository.php line 391:
This cache store does not support tagging.
```

This is happening because I am using the default `CACHE_DRIVER=file` which doesn't support tagging. I would've really liked it if this contained a fallback for this driver, or if this was contained in another branch.

**Comment by screencom** [comment]
Hi,

I said i'd send you some code. It's fairly simple. Each time we make a 
modification to the ACL we flush the cache using our tags:

Cache::tags(config('acl.cacheTags', []))->flush();

We also use an artisan command acl:flush, which does the same in the 
handle() method. We can use this during deploy.

-- 
Kind regards,

Michiel van Leening
Senior Systems Architect
logo_screencom <http://www.screencom.eu/>samsung_miip_reseller
Hoogveen 3-5
9501 XK Stadskanaal
The Netherlands
T. +31(0)85 273 64 28
m.vanleening@screencom.eu <mailto:m.vanleening@screencom.eu>

**Comment by WickedSik** [comment]
@screencom @kodeine While I like the change, can someone update this code ASAP to allow non-tagging caches, I need to lock `kodeine/laravel-acl` to a specific commit now. ( I am not setting `CACHE_DRIVER=array` for production systems!

**Comment by screencom** [comment]
@WickedSik I didn't plan for this eventuality and am not responsible for merging this into master. I think it's best if @kodeine fixes this.

It could use something along the lines of this : https://stackoverflow.com/a/39528746/650526

**Comment by kodeine** [comment]
i will find a fix and merge again until then i am reverting this.

**Pull request merged**
