### PR TITLE
Removed use of in_array()

### PR DESCRIPTION
**Pull request by lokimo**
resolves kodeine/laravel-acl#120

### CODE REVIEW

**Comment by kodeine** [comment]
@lokimo 
were you able to test this on 5.1 and 5.0 for backwards compatibility?

**Comment by kodeine** [comment]
@lokimo 
i just checked, its not compatible with 5.1, you have any other solution in mind?

**Comment by lokimo** [comment]
true, maybe something like

    if ( ! is_array($roles) ) {
        $roles = $roles->toArray();
    }

after retrieving the roles. 
(also this might be interesting: laravel/framework/issues/9269)

**Comment by peetersdiet** [comment]
@kodeine @lokimo: What are the issues with a straight-forward array-cast? I tested the cast on Laravel 5.2 and it works just fine.

`return in_array($slug, (array) $roles);`

**Comment by peetersdiet** [comment]
@kodeine We are also using Laravel 5.2. and are interested in this fix. Do you have any timeframe when this will be merged?

**Comment by kodeine** [comment]
@peetersdiet @lokimo 
can you guys please test on 5.1 and 5.2 and i'll merge the change?

**Comment by kodeine** [comment]
@peetersdiet does it work with `return in_array($slug, (array) $roles);` can you test on 5.1?

**Comment by peetersdiet** [comment]
@kodeine No, the array-casting does not work as intended. I was a bit too quick in proposing it. That's why I deleted the comment.

I cannot test on 5.1, but if you add an instanceof check, I am quite sure the existing code will stay BC.

`if ( ! is_array($roles) && $roles instanceof \Illuminate\Support\Collection) {
    $roles = $roles->toArray();
}`

**Comment by peetersdiet** [comment]
You could also target the toArray method specifically by testing for the interface defining toArray.

```php
if ($roles instanceof \Illuminate\Contracts\Support\Arrayable) {
...

**Comment by kodeine** [comment]
@peetersdiet is it possible for you to send a PR, im not on my pc so it will take me sometime to make changes?

**Comment by peetersdiet** [comment]
@kodeine Here you go: kodeine/laravel-acl#139 Tested only in Laravel 5.2.

Btw, I do see the array-cast already in the code, but that does not work as expected for objects (it will just create a shallow array of the object-properties). So for Laravel 5.2 the only fix is to explicitely call the toArray-method, as @lokimo proposed.

**Comment by Messhias** [comment]
This project seems to be abandoned, so I forked to my open-source saver organization and we're willing to continue the contribution of the project, we did that already before with Tymon's Design JWT package for laravel. 

You can access the package here -> https://github.com/kodeine/laravel-acl/pull/266

**Comment by kodeine** [comment]
This was resolved and merged already a while ago

**Pull request closed without merging**
